[window]
# opacity = 0.9
[window.padding]
y = 6
x = 6

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 14

[colors.primary]
# Hard dark background for better contrast
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"
